### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by asclines** [lord63/isitup#2]
Upon running `isitup` initially, I received this warning.

```bash
InsecurePlatformWarning: A true [135/661]
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
```

Now I did fix this, but I am writing up this issue to help others who may come across this.
I received this error when installing using `pip install isitup` as is stated to do in the instructions. However, I have Python 2.7 **and** Python 3.4 installed on my machine, the default `pip` for me installed isitup for Python 2.7.

The problem was fixed when I ran these lines:
```bash
pip uninstall isitup  
pip3 install isitup
```

I would also recommend the reader first making sure pip is updated and installed for Python 3 by following [these instructions](https://pip.pypa.io/en/stable/installing/) first.

**Comment by asclines** [comment]
If @lord63 would like, I'd be happy to Pull-Request into the readme with this troubleshooting help.

**Comment by lord63** [comment]
@asclines The reason for the warning is not for the `isitup` package, but for the old python version and outdated ssl module. You solved the problem by install `isitup` under python 3, but python 2.x should work fine, It works fine for python 2.7.13 on my machine. You can try to upgrade to the lastest python version or install some packages, see http://stackoverflow.com/q/29099404.

Thanks for your kind, sir :)
